#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqZ8EfM/SEsznA2MaO4kt2PQ9hLOnRQdO1Dj2u57HmLyRDPnpijI1o21+P1K2176sE13+77BBM4tfVy1hUZEHtT/qBywN4sgzG0HVMnKHMBPG2znBuftTk7vhgw8DC1VXM55a9FbZk6d5BQNg2IeUgffR7M+yRK3+odSapWcSmjfc+gMF9EaPeWfQTzOc+6Q9I/aP4rmuYpXCouZD15v9Xm4ctzJaLqzljeo7D9CTzXqHL1buZ+Mb9g+Iu9gtG0Bk0wiEaFIkMpNNl4fo6k+lPfaRjtWEbwaRy7JH6vAg3e3NunOcRn/vsR9UZ+iLtSmornqVlM5MOtDCQzBRKFzur aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
write_files:
  - encoding: b64
    path: /var/www/html/db.php
    content: PD9waHAKICAgICAgICAvL2RhdGFiYXNlCiAgICAgICAgJHNlcnZlcm5hbWUgPSAiNTQuMTYzLjIyNy4xMTgiOwogICAgICAgICR1c2VybmFtZSA9ICJhZG1pbiI7CiAgICAgICAgJHBhc3N3b3JkID0gInBhc3N3b3JkIjsKICAgICAgICAkZGJuYW1lID0gIm15c3FsIjsKCiAgICAgICAgLy8gQ3JlYXRlIGNvbm5lY3Rpb24KICAgICAgICAkY29ubiA9IG5ldyBteXNxbGkoJHNlcnZlcm5hbWUsICR1c2VybmFtZSwgJHBhc3N3b3JkLCAkZGJuYW1lKTsKICAgICAgICAvLyBDaGVjayBjb25uZWN0aW9uCiAgICAgICAgaWYgKCRjb25uLT5jb25uZWN0X2Vycm9yKSB7CiAgICAgICAgICAgICAgICBkaWUoIkNvbm5lY3Rpb24gZmFpbGVkOiAiIC4gJGNvbm4tPmNvbm5lY3RfZXJyb3IpOwogICAgICAgIH0KCiAgICAgICAgJHNxbCA9ICJzZWxlY3QgSG9zdCwgVXNlciBmcm9tIG15c3FsLnVzZXI7IjsKICAgICAgICAkcmVzdWx0ID0gJGNvbm4tPnF1ZXJ5KCRzcWwpOwogICAgICAgIHdoaWxlKCRyb3cgPSAkcmVzdWx0LT5mZXRjaF9hc3NvYygpKXsKICAgICAgICAgICAgICAgIGVjaG8oJHJvd1siSG9zdCJdIC4gIiAvICIgLiAkcm93WyJVc2VyIl0gLiAiPGJyIC8+Iik7CiAgICAgICAgfQogICAgICAgIC8vdmFyX2R1bXAoJHJlc3VsdCk7Cj8+Cg==
  - encoding: b64
    path: /var/www/html/info.php
    content: PD9waHAKCi8vIFNob3cgYWxsIGluZm9ybWF0aW9uLCBkZWZhdWx0cyB0byBJTkZPX0FMTApwaHBpbmZvKCk7Cgo/Pg==
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2