#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa xxxaaabbbcccxxx aws-key
  - name: tbz
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    home: /home/ubuntu
    shell: /bin/bash
timezone: EU/Central
locale: de_CH
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget