#cloud-config
users: # Collection uf users
  - name: ubuntu # name of user
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo rules for user
    groups: users, admin # group into user and admin group
    home: /home/ubuntu # home path
    shell: /bin/bash # the path for the shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqZ8EfM/SEsznA2MaO4kt2PQ9hLOnRQdO1Dj2u57HmLyRDPnpijI1o21+P1K2176sE13+77BBM4tfVy1hUZEHtT/qBywN4sgzG0HVMnKHMBPG2znBuftTk7vhgw8DC1VXM55a9FbZk6d5BQNg2IeUgffR7M+yRK3+odSapWcSmjfc+gMF9EaPeWfQTzOc+6Q9I/aP4rmuYpXCouZD15v9Xm4ctzJaLqzljeo7D9CTzXqHL1buZ+Mb9g+Iu9gtG0Bk0wiEaFIkMpNNl4fo6k+lPfaRjtWEbwaRy7JH6vAg3e3NunOcRn/vsR9UZ+iLtSmornqVlM5MOtDCQzBRKFzur aws-key # public key
ssh_pwauth: false # disable password authentication
disable_root: false # enable root
package_update: true # enable package update
packages:
  - curl # package name
  - wget # package name