#cloud-config
users: # Collection uf users
  - name: ubuntu # name of user
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo rules for user
    groups: users, admin # group into user and admin group
    home: /home/ubuntu # home path
    shell: /bin/bash # the path for the shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key # public key
ssh_pwauth: false # disable password authentication
disable_root: false # enable root
package_update: true # enable package update
packages:
  - curl # package name
  - wget # package name