#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqZ8EfM/SEsznA2MaO4kt2PQ9hLOnRQdO1Dj2u57HmLyRDPnpijI1o21+P1K2176sE13+77BBM4tfVy1hUZEHtT/qBywN4sgzG0HVMnKHMBPG2znBuftTk7vhgw8DC1VXM55a9FbZk6d5BQNg2IeUgffR7M+yRK3+odSapWcSmjfc+gMF9EaPeWfQTzOc+6Q9I/aP4rmuYpXCouZD15v9Xm4ctzJaLqzljeo7D9CTzXqHL1buZ+Mb9g+Iu9gtG0Bk0wiEaFIkMpNNl4fo6k+lPfaRjtWEbwaRy7JH6vAg3e3NunOcRn/vsR9UZ+iLtSmornqVlM5MOtDCQzBRKFzur aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
write_files:
  - encoding: b64
    path: /var/www/html/db.php
    content: PD9waHAKICAgICAgICAvL2RhdGFiYXNlCiAgICAgICAgJHNlcnZlcm5hbWUgPSAiMy44Ni4yMTkuMTExIjsKICAgICAgICAkdXNlcm5hbWUgPSAiYWRtaW4iOwogICAgICAgICRwYXNzd29yZCA9ICJwYXNzd29yZCI7CiAgICAgICAgJGRibmFtZSA9ICJteXNxbCI7CgogICAgICAgIC8vIENyZWF0ZSBjb25uZWN0aW9uCiAgICAgICAgJGNvbm4gPSBuZXcgbXlzcWxpKCRzZXJ2ZXJuYW1lLCAkdXNlcm5hbWUsICRwYXNzd29yZCwgJGRibmFtZSk7CiAgICAgICAgLy8gQ2hlY2sgY29ubmVjdGlvbgogICAgICAgIGlmICgkY29ubi0+Y29ubmVjdF9lcnJvcikgewogICAgICAgICAgICAgICAgZGllKCJDb25uZWN0aW9uIGZhaWxlZDogIiAuICRjb25uLT5jb25uZWN0X2Vycm9yKTsKICAgICAgICB9CgogICAgICAgICRzcWwgPSAic2VsZWN0IEhvc3QsIFVzZXIgZnJvbSBteXNxbC51c2VyOyI7CiAgICAgICAgJHJlc3VsdCA9ICRjb25uLT5xdWVyeSgkc3FsKTsKICAgICAgICB3aGlsZSgkcm93ID0gJHJlc3VsdC0+ZmV0Y2hfYXNzb2MoKSl7CiAgICAgICAgICAgICAgICBlY2hvKCRyb3dbIkhvc3QiXSAuICIgLyAiIC4gJHJvd1siVXNlciJdIC4gIjxiciAvPiIpOwogICAgICAgIH0KICAgICAgICAvL3Zhcl9kdW1wKCRyZXN1bHQpOwo/Pgo=
  - encoding: b64
    path: /var/www/html/info.php
    content: PD9waHAKCi8vIFNob3cgYWxsIGluZm9ybWF0aW9uLCBkZWZhdWx0cyB0byBJTkZPX0FMTApwaHBpbmZvKCk7Cgo/Pg==
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2